name: proyect_movil_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

flutter_native_splash:
  background_image: "assets/images/campus2.png"
  image: "assets/images/Utem.png"

  android_12:
    background_image: "assets/images/campus2.png"
    image: "assets/images/Utem.png"

dependencies:
  flutter:
    sdk: flutter
  api_cache_manager: ^1.0.2
  flutter_native_splash: ^2.2.3+1
  snippet_coder_utils: ^1.0.9
  mobile_scanner: ^2.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true
  assets:
    - assets/images/